#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/koihata.jpg
picom --experimental-backends &
fcitx5 &

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX


bspc config border_width        3 
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on

